project:
  name: adaptive-weighting-engine
  frequency: monthly
  start_date: "1998-12-22"
  end_date: "2026-06-22"

universe:
  etfs:
    - XLK
    - XLF
    - XLE
    - XLV
    - XLY
    - XLI
    - XLU
    - XLP
    - XLB
  benchmark: SPY
  optional_etfs:
    - XLRE
    - XLC
